version: "3.5"

networks: 
    net1:
        ipam: 
            driver: default
            config: 
            - subnet: 182.19.0.0/24

services: 
    hr-db:
        build: .
        image: mahendrshinde/mysql-sample:employees
        networks: 
            net1:
                ipv4_address: 182.19.0.5
